apiVersion: v1
kind: ConfigMap

metadata:
  name: fastapi-config

data:
  APP_NAME: "Docker Kubernetes API"
  APP_ENV: "development"
  LOG_LEVEL: "INFO"
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"